
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "Kishor@123"
  host: localhost

development:
  <<: *default
  database: task_management_api_development12

test:
  <<: *default
  database: task_management_api_test

production:
  <<: *default
  database: task_management_api_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>